name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: "https://registry.npmjs.org"
      - name: Se instalan dependencias npm install
        run: npm install
      - name: Publish to npm
        run: npm release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
